/* automatically generated by rust-bindgen 0.69.4 */

pub const MU_VERSION: &[u8; 5] = b"2.01\0";
pub const MU_COMMANDLIST_SIZE: u32 = 262144;
pub const MU_ROOTLIST_SIZE: u32 = 32;
pub const MU_CONTAINERSTACK_SIZE: u32 = 32;
pub const MU_CLIPSTACK_SIZE: u32 = 32;
pub const MU_IDSTACK_SIZE: u32 = 32;
pub const MU_LAYOUTSTACK_SIZE: u32 = 16;
pub const MU_CONTAINERPOOL_SIZE: u32 = 48;
pub const MU_TREENODEPOOL_SIZE: u32 = 48;
pub const MU_MAX_WIDTHS: u32 = 16;
pub const MU_REAL_FMT: &[u8; 5] = b"%.3g\0";
pub const MU_SLIDER_FMT: &[u8; 5] = b"%.2f\0";
pub const MU_MAX_FMT: u32 = 127;
pub const MU_CLIP_PART: _bindgen_ty_1 = 1;
pub const MU_CLIP_ALL: _bindgen_ty_1 = 2;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
pub const MU_COMMAND_JUMP: _bindgen_ty_2 = 1;
pub const MU_COMMAND_CLIP: _bindgen_ty_2 = 2;
pub const MU_COMMAND_RECT: _bindgen_ty_2 = 3;
pub const MU_COMMAND_TEXT: _bindgen_ty_2 = 4;
pub const MU_COMMAND_ICON: _bindgen_ty_2 = 5;
pub const MU_COMMAND_MAX: _bindgen_ty_2 = 6;
pub type _bindgen_ty_2 = ::core::ffi::c_uint;
pub const MU_COLOR_TEXT: _bindgen_ty_3 = 0;
pub const MU_COLOR_BORDER: _bindgen_ty_3 = 1;
pub const MU_COLOR_WINDOWBG: _bindgen_ty_3 = 2;
pub const MU_COLOR_TITLEBG: _bindgen_ty_3 = 3;
pub const MU_COLOR_TITLETEXT: _bindgen_ty_3 = 4;
pub const MU_COLOR_PANELBG: _bindgen_ty_3 = 5;
pub const MU_COLOR_BUTTON: _bindgen_ty_3 = 6;
pub const MU_COLOR_BUTTONHOVER: _bindgen_ty_3 = 7;
pub const MU_COLOR_BUTTONFOCUS: _bindgen_ty_3 = 8;
pub const MU_COLOR_BASE: _bindgen_ty_3 = 9;
pub const MU_COLOR_BASEHOVER: _bindgen_ty_3 = 10;
pub const MU_COLOR_BASEFOCUS: _bindgen_ty_3 = 11;
pub const MU_COLOR_SCROLLBASE: _bindgen_ty_3 = 12;
pub const MU_COLOR_SCROLLTHUMB: _bindgen_ty_3 = 13;
pub const MU_COLOR_MAX: _bindgen_ty_3 = 14;
pub type _bindgen_ty_3 = ::core::ffi::c_uint;
pub const MU_ICON_CLOSE: _bindgen_ty_4 = 1;
pub const MU_ICON_CHECK: _bindgen_ty_4 = 2;
pub const MU_ICON_COLLAPSED: _bindgen_ty_4 = 3;
pub const MU_ICON_EXPANDED: _bindgen_ty_4 = 4;
pub const MU_ICON_MAX: _bindgen_ty_4 = 5;
pub type _bindgen_ty_4 = ::core::ffi::c_uint;
pub const MU_RES_ACTIVE: _bindgen_ty_5 = 1;
pub const MU_RES_SUBMIT: _bindgen_ty_5 = 2;
pub const MU_RES_CHANGE: _bindgen_ty_5 = 4;
pub type _bindgen_ty_5 = ::core::ffi::c_uint;
pub const MU_OPT_ALIGNCENTER: _bindgen_ty_6 = 1;
pub const MU_OPT_ALIGNRIGHT: _bindgen_ty_6 = 2;
pub const MU_OPT_NOINTERACT: _bindgen_ty_6 = 4;
pub const MU_OPT_NOFRAME: _bindgen_ty_6 = 8;
pub const MU_OPT_NORESIZE: _bindgen_ty_6 = 16;
pub const MU_OPT_NOSCROLL: _bindgen_ty_6 = 32;
pub const MU_OPT_NOCLOSE: _bindgen_ty_6 = 64;
pub const MU_OPT_NOTITLE: _bindgen_ty_6 = 128;
pub const MU_OPT_HOLDFOCUS: _bindgen_ty_6 = 256;
pub const MU_OPT_AUTOSIZE: _bindgen_ty_6 = 512;
pub const MU_OPT_POPUP: _bindgen_ty_6 = 1024;
pub const MU_OPT_CLOSED: _bindgen_ty_6 = 2048;
pub const MU_OPT_EXPANDED: _bindgen_ty_6 = 4096;
pub type _bindgen_ty_6 = ::core::ffi::c_uint;
pub const MU_MOUSE_LEFT: _bindgen_ty_7 = 1;
pub const MU_MOUSE_RIGHT: _bindgen_ty_7 = 2;
pub const MU_MOUSE_MIDDLE: _bindgen_ty_7 = 4;
pub type _bindgen_ty_7 = ::core::ffi::c_uint;
pub const MU_KEY_SHIFT: _bindgen_ty_8 = 1;
pub const MU_KEY_CTRL: _bindgen_ty_8 = 2;
pub const MU_KEY_ALT: _bindgen_ty_8 = 4;
pub const MU_KEY_BACKSPACE: _bindgen_ty_8 = 8;
pub const MU_KEY_RETURN: _bindgen_ty_8 = 16;
pub type _bindgen_ty_8 = ::core::ffi::c_uint;
pub type mu_Id = ::core::ffi::c_uint;
pub type mu_Real = f32;
pub type mu_Font = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Vec2 {
    pub x: ::core::ffi::c_int,
    pub y: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_Vec2() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Vec2> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Vec2>(),
        8usize,
        concat!("Size of: ", stringify!(mu_Vec2))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Vec2>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Vec2))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).x) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Vec2),
            "::",
            stringify!(x)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).y) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Vec2),
            "::",
            stringify!(y)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Rect {
    pub x: ::core::ffi::c_int,
    pub y: ::core::ffi::c_int,
    pub w: ::core::ffi::c_int,
    pub h: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_Rect() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Rect> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Rect>(),
        16usize,
        concat!("Size of: ", stringify!(mu_Rect))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Rect>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Rect))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).x) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Rect),
            "::",
            stringify!(x)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).y) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Rect),
            "::",
            stringify!(y)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).w) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Rect),
            "::",
            stringify!(w)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).h) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Rect),
            "::",
            stringify!(h)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Color {
    pub r: ::core::ffi::c_uchar,
    pub g: ::core::ffi::c_uchar,
    pub b: ::core::ffi::c_uchar,
    pub a: ::core::ffi::c_uchar,
}
#[test]
fn bindgen_test_layout_mu_Color() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Color> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Color>(),
        4usize,
        concat!("Size of: ", stringify!(mu_Color))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Color>(),
        1usize,
        concat!("Alignment of ", stringify!(mu_Color))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).r) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Color),
            "::",
            stringify!(r)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).g) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Color),
            "::",
            stringify!(g)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).b) as usize - ptr as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Color),
            "::",
            stringify!(b)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).a) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Color),
            "::",
            stringify!(a)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_PoolItem {
    pub id: mu_Id,
    pub last_update: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_PoolItem() {
    const UNINIT: ::core::mem::MaybeUninit<mu_PoolItem> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_PoolItem>(),
        8usize,
        concat!("Size of: ", stringify!(mu_PoolItem))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_PoolItem>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_PoolItem))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_PoolItem),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).last_update) as usize - ptr as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_PoolItem),
            "::",
            stringify!(last_update)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_BaseCommand {
    pub type_: ::core::ffi::c_int,
    pub size: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_BaseCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_BaseCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_BaseCommand>(),
        8usize,
        concat!("Size of: ", stringify!(mu_BaseCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_BaseCommand>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_BaseCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_BaseCommand),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_BaseCommand),
            "::",
            stringify!(size)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_JumpCommand {
    pub base: mu_BaseCommand,
    pub dst: *mut ::core::ffi::c_void,
}
#[test]
fn bindgen_test_layout_mu_JumpCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_JumpCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_JumpCommand>(),
        16usize,
        concat!("Size of: ", stringify!(mu_JumpCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_JumpCommand>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_JumpCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_JumpCommand),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).dst) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_JumpCommand),
            "::",
            stringify!(dst)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_ClipCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
}
#[test]
fn bindgen_test_layout_mu_ClipCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_ClipCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_ClipCommand>(),
        24usize,
        concat!("Size of: ", stringify!(mu_ClipCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_ClipCommand>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_ClipCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_ClipCommand),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).rect) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_ClipCommand),
            "::",
            stringify!(rect)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_RectCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
    pub color: mu_Color,
}
#[test]
fn bindgen_test_layout_mu_RectCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_RectCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_RectCommand>(),
        28usize,
        concat!("Size of: ", stringify!(mu_RectCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_RectCommand>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_RectCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_RectCommand),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).rect) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_RectCommand),
            "::",
            stringify!(rect)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).color) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_RectCommand),
            "::",
            stringify!(color)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_TextCommand {
    pub base: mu_BaseCommand,
    pub font: mu_Font,
    pub pos: mu_Vec2,
    pub color: mu_Color,
    pub str_: [::core::ffi::c_char; 1usize],
}
#[test]
fn bindgen_test_layout_mu_TextCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_TextCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_TextCommand>(),
        32usize,
        concat!("Size of: ", stringify!(mu_TextCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_TextCommand>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_TextCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_TextCommand),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).font) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_TextCommand),
            "::",
            stringify!(font)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).pos) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_TextCommand),
            "::",
            stringify!(pos)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).color) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_TextCommand),
            "::",
            stringify!(color)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).str_) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_TextCommand),
            "::",
            stringify!(str_)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_IconCommand {
    pub base: mu_BaseCommand,
    pub rect: mu_Rect,
    pub id: ::core::ffi::c_int,
    pub color: mu_Color,
}
#[test]
fn bindgen_test_layout_mu_IconCommand() {
    const UNINIT: ::core::mem::MaybeUninit<mu_IconCommand> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_IconCommand>(),
        32usize,
        concat!("Size of: ", stringify!(mu_IconCommand))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_IconCommand>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_IconCommand))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_IconCommand),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).rect) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_IconCommand),
            "::",
            stringify!(rect)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_IconCommand),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).color) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_IconCommand),
            "::",
            stringify!(color)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mu_Command {
    pub type_: ::core::ffi::c_int,
    pub base: mu_BaseCommand,
    pub jump: mu_JumpCommand,
    pub clip: mu_ClipCommand,
    pub rect: mu_RectCommand,
    pub text: mu_TextCommand,
    pub icon: mu_IconCommand,
}
#[test]
fn bindgen_test_layout_mu_Command() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Command> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Command>(),
        32usize,
        concat!("Size of: ", stringify!(mu_Command))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Command>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Command))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).base) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(base)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).jump) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(jump)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).clip) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(clip)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).rect) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(rect)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).text) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(text)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).icon) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Command),
            "::",
            stringify!(icon)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Layout {
    pub body: mu_Rect,
    pub next: mu_Rect,
    pub position: mu_Vec2,
    pub size: mu_Vec2,
    pub max: mu_Vec2,
    pub widths: [::core::ffi::c_int; 16usize],
    pub items: ::core::ffi::c_int,
    pub item_index: ::core::ffi::c_int,
    pub next_row: ::core::ffi::c_int,
    pub next_type: ::core::ffi::c_int,
    pub indent: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_Layout() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Layout> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Layout>(),
        140usize,
        concat!("Size of: ", stringify!(mu_Layout))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Layout>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Layout))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).body) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(body)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).next) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(next)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).position) as usize - ptr as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(position)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).max) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(max)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).widths) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(widths)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(items)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).item_index) as usize - ptr as usize
        },
        124usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(item_index)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).next_row) as usize - ptr as usize
        },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(next_row)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).next_type) as usize - ptr as usize
        },
        132usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(next_type)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).indent) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Layout),
            "::",
            stringify!(indent)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Container {
    pub head: *mut mu_Command,
    pub tail: *mut mu_Command,
    pub rect: mu_Rect,
    pub body: mu_Rect,
    pub content_size: mu_Vec2,
    pub scroll: mu_Vec2,
    pub zindex: ::core::ffi::c_int,
    pub open: ::core::ffi::c_int,
}
#[test]
fn bindgen_test_layout_mu_Container() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Container> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Container>(),
        72usize,
        concat!("Size of: ", stringify!(mu_Container))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Container>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Container))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).head) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(head)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).tail) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(tail)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).rect) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(rect)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).body) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(body)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).content_size) as usize - ptr as usize
        },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(content_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).scroll) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(scroll)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).zindex) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(zindex)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).open) as usize - ptr as usize },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Container),
            "::",
            stringify!(open)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Style {
    pub font: mu_Font,
    pub size: mu_Vec2,
    pub padding: ::core::ffi::c_int,
    pub spacing: ::core::ffi::c_int,
    pub indent: ::core::ffi::c_int,
    pub title_height: ::core::ffi::c_int,
    pub scrollbar_size: ::core::ffi::c_int,
    pub thumb_size: ::core::ffi::c_int,
    pub colors: [mu_Color; 14usize],
}
#[test]
fn bindgen_test_layout_mu_Style() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Style> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Style>(),
        96usize,
        concat!("Size of: ", stringify!(mu_Style))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Style>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Style))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).font) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(font)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).padding) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(padding)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).spacing) as usize - ptr as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(spacing)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).indent) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(indent)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).title_height) as usize - ptr as usize
        },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(title_height)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).scrollbar_size) as usize - ptr as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(scrollbar_size)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).thumb_size) as usize - ptr as usize
        },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(thumb_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).colors) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Style),
            "::",
            stringify!(colors)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context {
    pub text_width: ::core::option::Option<
        unsafe extern "C" fn(
            font: mu_Font,
            str_: *const ::core::ffi::c_char,
            len: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub text_height: ::core::option::Option<
        unsafe extern "C" fn(font: mu_Font) -> ::core::ffi::c_int,
    >,
    pub draw_frame: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut mu_Context,
            rect: mu_Rect,
            colorid: ::core::ffi::c_int,
        ),
    >,
    pub _style: mu_Style,
    pub style: *mut mu_Style,
    pub hover: mu_Id,
    pub focus: mu_Id,
    pub last_id: mu_Id,
    pub last_rect: mu_Rect,
    pub last_zindex: ::core::ffi::c_int,
    pub updated_focus: ::core::ffi::c_int,
    pub frame: ::core::ffi::c_int,
    pub hover_root: *mut mu_Container,
    pub next_hover_root: *mut mu_Container,
    pub scroll_target: *mut mu_Container,
    pub number_edit_buf: [::core::ffi::c_char; 127usize],
    pub number_edit: mu_Id,
    pub command_list: mu_Context__bindgen_ty_1,
    pub root_list: mu_Context__bindgen_ty_2,
    pub container_stack: mu_Context__bindgen_ty_3,
    pub clip_stack: mu_Context__bindgen_ty_4,
    pub id_stack: mu_Context__bindgen_ty_5,
    pub layout_stack: mu_Context__bindgen_ty_6,
    pub container_pool: [mu_PoolItem; 48usize],
    pub containers: [mu_Container; 48usize],
    pub treenode_pool: [mu_PoolItem; 48usize],
    pub mouse_pos: mu_Vec2,
    pub last_mouse_pos: mu_Vec2,
    pub mouse_delta: mu_Vec2,
    pub scroll_delta: mu_Vec2,
    pub mouse_down: ::core::ffi::c_int,
    pub mouse_pressed: ::core::ffi::c_int,
    pub key_down: ::core::ffi::c_int,
    pub key_pressed: ::core::ffi::c_int,
    pub input_text: [::core::ffi::c_char; 32usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_1 {
    pub idx: ::core::ffi::c_int,
    pub items: [::core::ffi::c_char; 262144usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_1() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_1> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_1>(),
        262148usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_1))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_1>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_1),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_1),
            "::",
            stringify!(items)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_2 {
    pub idx: ::core::ffi::c_int,
    pub items: [*mut mu_Container; 32usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_2() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_2> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_2>(),
        264usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_2))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_2>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_2))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_2),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_2),
            "::",
            stringify!(items)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_3 {
    pub idx: ::core::ffi::c_int,
    pub items: [*mut mu_Container; 32usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_3() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_3> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_3>(),
        264usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_3))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_3>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_3))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_3),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_3),
            "::",
            stringify!(items)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_4 {
    pub idx: ::core::ffi::c_int,
    pub items: [mu_Rect; 32usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_4() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_4> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_4>(),
        516usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_4))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_4>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_4))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_4),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_4),
            "::",
            stringify!(items)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_5 {
    pub idx: ::core::ffi::c_int,
    pub items: [mu_Id; 32usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_5() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_5> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_5>(),
        132usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_5))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_5>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_5))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_5),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_5),
            "::",
            stringify!(items)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mu_Context__bindgen_ty_6 {
    pub idx: ::core::ffi::c_int,
    pub items: [mu_Layout; 16usize],
}
#[test]
fn bindgen_test_layout_mu_Context__bindgen_ty_6() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context__bindgen_ty_6> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context__bindgen_ty_6>(),
        2244usize,
        concat!("Size of: ", stringify!(mu_Context__bindgen_ty_6))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context__bindgen_ty_6>(),
        4usize,
        concat!("Alignment of ", stringify!(mu_Context__bindgen_ty_6))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).idx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_6),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).items) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context__bindgen_ty_6),
            "::",
            stringify!(items)
        )
    );
}
#[test]
fn bindgen_test_layout_mu_Context() {
    const UNINIT: ::core::mem::MaybeUninit<mu_Context> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<mu_Context>(),
        270200usize,
        concat!("Size of: ", stringify!(mu_Context))
    );
    assert_eq!(
        ::core::mem::align_of::<mu_Context>(),
        8usize,
        concat!("Alignment of ", stringify!(mu_Context))
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).text_width) as usize - ptr as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(text_width)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).text_height) as usize - ptr as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(text_height)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).draw_frame) as usize - ptr as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(draw_frame)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr)._style) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(_style)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).style) as usize - ptr as usize },
        120usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(style)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).hover) as usize - ptr as usize },
        128usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(hover)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).focus) as usize - ptr as usize },
        132usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(focus)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).last_id) as usize - ptr as usize
        },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(last_id)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).last_rect) as usize - ptr as usize
        },
        140usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(last_rect)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).last_zindex) as usize - ptr as usize
        },
        156usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(last_zindex)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).updated_focus) as usize - ptr as usize
        },
        160usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(updated_focus)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).frame) as usize - ptr as usize },
        164usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(frame)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).hover_root) as usize - ptr as usize
        },
        168usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(hover_root)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).next_hover_root) as usize
                - ptr as usize
        },
        176usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(next_hover_root)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).scroll_target) as usize - ptr as usize
        },
        184usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(scroll_target)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).number_edit_buf) as usize
                - ptr as usize
        },
        192usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(number_edit_buf)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).number_edit) as usize - ptr as usize
        },
        320usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(number_edit)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).command_list) as usize - ptr as usize
        },
        324usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(command_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).root_list) as usize - ptr as usize
        },
        262472usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(root_list)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).container_stack) as usize
                - ptr as usize
        },
        262736usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(container_stack)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).clip_stack) as usize - ptr as usize
        },
        263000usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(clip_stack)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).id_stack) as usize - ptr as usize
        },
        263516usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(id_stack)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).layout_stack) as usize - ptr as usize
        },
        263648usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(layout_stack)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).container_pool) as usize - ptr as usize
        },
        265892usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(container_pool)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).containers) as usize - ptr as usize
        },
        266280usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(containers)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).treenode_pool) as usize - ptr as usize
        },
        269736usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(treenode_pool)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).mouse_pos) as usize - ptr as usize
        },
        270120usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(mouse_pos)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).last_mouse_pos) as usize - ptr as usize
        },
        270128usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(last_mouse_pos)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).mouse_delta) as usize - ptr as usize
        },
        270136usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(mouse_delta)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).scroll_delta) as usize - ptr as usize
        },
        270144usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(scroll_delta)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).mouse_down) as usize - ptr as usize
        },
        270152usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(mouse_down)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).mouse_pressed) as usize - ptr as usize
        },
        270156usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(mouse_pressed)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).key_down) as usize - ptr as usize
        },
        270160usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(key_down)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).key_pressed) as usize - ptr as usize
        },
        270164usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(key_pressed)
        )
    );
    assert_eq!(
        unsafe {
            ::core::ptr::addr_of!((*ptr).input_text) as usize - ptr as usize
        },
        270168usize,
        concat!(
            "Offset of field: ",
            stringify!(mu_Context),
            "::",
            stringify!(input_text)
        )
    );
}
extern "C" {
    pub fn mu_vec2(x: ::core::ffi::c_int, y: ::core::ffi::c_int) -> mu_Vec2;
}
extern "C" {
    pub fn mu_rect(
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
        w: ::core::ffi::c_int,
        h: ::core::ffi::c_int,
    ) -> mu_Rect;
}
extern "C" {
    pub fn mu_color(
        r: ::core::ffi::c_int,
        g: ::core::ffi::c_int,
        b: ::core::ffi::c_int,
        a: ::core::ffi::c_int,
    ) -> mu_Color;
}
extern "C" {
    pub fn mu_init(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_begin(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_end(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_set_focus(ctx: *mut mu_Context, id: mu_Id);
}
extern "C" {
    pub fn mu_get_id(
        ctx: *mut mu_Context,
        data: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    ) -> mu_Id;
}
extern "C" {
    pub fn mu_push_id(
        ctx: *mut mu_Context,
        data: *const ::core::ffi::c_void,
        size: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_pop_id(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_push_clip_rect(ctx: *mut mu_Context, rect: mu_Rect);
}
extern "C" {
    pub fn mu_pop_clip_rect(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_get_clip_rect(ctx: *mut mu_Context) -> mu_Rect;
}
extern "C" {
    pub fn mu_check_clip(
        ctx: *mut mu_Context,
        r: mu_Rect,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_get_current_container(ctx: *mut mu_Context) -> *mut mu_Container;
}
extern "C" {
    pub fn mu_get_container(
        ctx: *mut mu_Context,
        name: *const ::core::ffi::c_char,
    ) -> *mut mu_Container;
}
extern "C" {
    pub fn mu_bring_to_front(ctx: *mut mu_Context, cnt: *mut mu_Container);
}
extern "C" {
    pub fn mu_pool_init(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        len: ::core::ffi::c_int,
        id: mu_Id,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_pool_get(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        len: ::core::ffi::c_int,
        id: mu_Id,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_pool_update(
        ctx: *mut mu_Context,
        items: *mut mu_PoolItem,
        idx: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_input_mousemove(
        ctx: *mut mu_Context,
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_input_mousedown(
        ctx: *mut mu_Context,
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
        btn: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_input_mouseup(
        ctx: *mut mu_Context,
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
        btn: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_input_scroll(
        ctx: *mut mu_Context,
        x: ::core::ffi::c_int,
        y: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_input_keydown(ctx: *mut mu_Context, key: ::core::ffi::c_int);
}
extern "C" {
    pub fn mu_input_keyup(ctx: *mut mu_Context, key: ::core::ffi::c_int);
}
extern "C" {
    pub fn mu_input_text(
        ctx: *mut mu_Context,
        text: *const ::core::ffi::c_char,
    );
}
extern "C" {
    pub fn mu_push_command(
        ctx: *mut mu_Context,
        type_: ::core::ffi::c_int,
        size: ::core::ffi::c_int,
    ) -> *mut mu_Command;
}
extern "C" {
    pub fn mu_next_command(
        ctx: *mut mu_Context,
        cmd: *mut *mut mu_Command,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_set_clip(ctx: *mut mu_Context, rect: mu_Rect);
}
extern "C" {
    pub fn mu_draw_rect(ctx: *mut mu_Context, rect: mu_Rect, color: mu_Color);
}
extern "C" {
    pub fn mu_draw_box(ctx: *mut mu_Context, rect: mu_Rect, color: mu_Color);
}
extern "C" {
    pub fn mu_draw_text(
        ctx: *mut mu_Context,
        font: mu_Font,
        str_: *const ::core::ffi::c_char,
        len: ::core::ffi::c_int,
        pos: mu_Vec2,
        color: mu_Color,
    );
}
extern "C" {
    pub fn mu_draw_icon(
        ctx: *mut mu_Context,
        id: ::core::ffi::c_int,
        rect: mu_Rect,
        color: mu_Color,
    );
}
extern "C" {
    pub fn mu_layout_row(
        ctx: *mut mu_Context,
        items: ::core::ffi::c_int,
        widths: *const ::core::ffi::c_int,
        height: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_layout_width(ctx: *mut mu_Context, width: ::core::ffi::c_int);
}
extern "C" {
    pub fn mu_layout_height(ctx: *mut mu_Context, height: ::core::ffi::c_int);
}
extern "C" {
    pub fn mu_layout_begin_column(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_layout_end_column(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_layout_set_next(
        ctx: *mut mu_Context,
        r: mu_Rect,
        relative: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_layout_next(ctx: *mut mu_Context) -> mu_Rect;
}
extern "C" {
    pub fn mu_draw_control_frame(
        ctx: *mut mu_Context,
        id: mu_Id,
        rect: mu_Rect,
        colorid: ::core::ffi::c_int,
        opt: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_draw_control_text(
        ctx: *mut mu_Context,
        str_: *const ::core::ffi::c_char,
        rect: mu_Rect,
        colorid: ::core::ffi::c_int,
        opt: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_mouse_over(
        ctx: *mut mu_Context,
        rect: mu_Rect,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_update_control(
        ctx: *mut mu_Context,
        id: mu_Id,
        rect: mu_Rect,
        opt: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_text(ctx: *mut mu_Context, text: *const ::core::ffi::c_char);
}
extern "C" {
    pub fn mu_label(ctx: *mut mu_Context, text: *const ::core::ffi::c_char);
}
extern "C" {
    pub fn mu_button_ex(
        ctx: *mut mu_Context,
        label: *const ::core::ffi::c_char,
        icon: ::core::ffi::c_int,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_checkbox(
        ctx: *mut mu_Context,
        label: *const ::core::ffi::c_char,
        state: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_textbox_raw(
        ctx: *mut mu_Context,
        buf: *mut ::core::ffi::c_char,
        bufsz: ::core::ffi::c_int,
        id: mu_Id,
        r: mu_Rect,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_textbox_ex(
        ctx: *mut mu_Context,
        buf: *mut ::core::ffi::c_char,
        bufsz: ::core::ffi::c_int,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_slider_ex(
        ctx: *mut mu_Context,
        value: *mut mu_Real,
        low: mu_Real,
        high: mu_Real,
        step: mu_Real,
        fmt: *const ::core::ffi::c_char,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_number_ex(
        ctx: *mut mu_Context,
        value: *mut mu_Real,
        step: mu_Real,
        fmt: *const ::core::ffi::c_char,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_header_ex(
        ctx: *mut mu_Context,
        label: *const ::core::ffi::c_char,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_begin_treenode_ex(
        ctx: *mut mu_Context,
        label: *const ::core::ffi::c_char,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_end_treenode(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_begin_window_ex(
        ctx: *mut mu_Context,
        title: *const ::core::ffi::c_char,
        rect: mu_Rect,
        opt: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_end_window(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_open_popup(
        ctx: *mut mu_Context,
        name: *const ::core::ffi::c_char,
    );
}
extern "C" {
    pub fn mu_begin_popup(
        ctx: *mut mu_Context,
        name: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn mu_end_popup(ctx: *mut mu_Context);
}
extern "C" {
    pub fn mu_begin_panel_ex(
        ctx: *mut mu_Context,
        name: *const ::core::ffi::c_char,
        opt: ::core::ffi::c_int,
    );
}
extern "C" {
    pub fn mu_end_panel(ctx: *mut mu_Context);
}
